### ISSUE TITLE
GameMaster: Score scrollbar

### ISSUE THREAD

**Issue by humanamburu** [games4nerds/_qd-ui#11]
![](https://i.imgur.com/dXagTDa.png)

**Comment by kirilknysh** [comment]
The layout is still nice! do not use windows - that would solve the issue :)

**Comment by kirilknysh** [comment]
mac os regular
![image](https://cloud.githubusercontent.com/assets/3236551/23528702/23708e14-ff9b-11e6-9759-c351aeae07ed.png)

hovered:

![image](https://cloud.githubusercontent.com/assets/3236551/23528723/313be7d2-ff9b-11e6-86f7-aef43eec2fe3.png)

**Comment by humanamburu** [comment]
https://github.com/21-23/_qd-ui/pull/32
