### ISSUE TITLE
hyperscript vs jsx

### ISSUE THREAD

**Issue by kirilknysh** [games4nerds/_qd-ui#15]
Replace jsx with  [hyperscript](https://github.com/Jador/react-hyperscript-helpers) ?

**Comment by lesnitsky** [comment]
Looks like `jsx` is more sweet sugar over `React.createClass` 😏

**Comment by kirilknysh** [comment]
👍 2 : 3 😕. Closing

**Comment by DaQuirm** [comment]
It's centennial October Revolution anniversary, bolsheviks have won again and the defeated minority has to live in exile in emigration 😿

**Comment by kirilknysh** [comment]
In your (my) case - vice versa: started with emigration 🇩🇪 (🇳🇱)
